### ISSUE TITLE
installed latest release v6.64.3_B23090710 in magisk but there's no mixplorer 

### ISSUE THREAD

**Issue by elvisisvan** [Psk-Ita/MiXplorer#16]
installed package: https://github.com/Psk-Ita/MiXplorer/commit/aebaab0e0ae0e91401349602e1bb484761cd8e34
device: google pixel 7 pro
android version: 13 (TQ3A.230705.001)
magisk version: 27.0 (27000)

i installed the package in magisk and rebooted but then there's no mixplorer installed, only the "mix signer", "mix metadata", "mix smb" appear in system;
![Screenshot_20240312-235418](https://github.com/Psk-Ita/MiXplorer/assets/69122770/ef9d19ad-d0d8-4193-ae24-81b6a9ae340e)

i have not installed mixplorer on the device prior to this, should i have installed regular version on mixplorer before installing this package via magisk?

**Comment by Psk-Ita** [comment]
the new version fix the problem
(unfortunately now the module size is increased because i embedded all feature directly, instead of downloading the required ones at runtime)

**Comment by elvisisvan** [comment]
> the new version fix the problem
> (unfortunately now the module size is increased because i embedded all feature directly, instead of downloading the required ones at runtime)

thanks for the fix, and no i don't think it's unfortunate, 43 megabytes is not that much, that's how it should be because the mixplorer package itself is already 10+ megabytes;

moreover this is a bundle, i should have noticed the little size of the archive package i installed when i saw mixplorer was not installed

**Comment by elvisisvan** [comment]
> the new version fix the problem
> (unfortunately now the module size is increased because i embedded all feature directly, instead of downloading the required ones at runtime)

thanks for the fix, and no i don't think it's unfortunate, 43 megabytes is not that much, that's how it should be because the mixplorer app itself is already 30+ megabytes

**Comment by Psk-Ita** [comment]
now the package contails all resources
you can try unzipping, open the tmp folder and install the interested assets

in v-30 there is mixplorer (for newest roms)
on v-29 (if you are running A11)

arm-64 contains all modern roms features
arm (same assets for 32bit legacy devices)

the tmp folder contains "invariant" assets

maybe the issue is related to installing process of your rom, manual installation should notice you about the error
