### ISSUE TITLE
Enhancement: separate page color for focused vs unfocused tab

### ISSUE THREAD

**Issue by derei** [Psk-Ita/MiXplorer#21]
If is not too much to ask, the following enhancement could prove itself immensely useful: separate color for focused and unfocused page. Yes, the tab marker shows which tab has focus, but it takes additional effort to associate the active tab with either left or right panel.
Thank you.

**Comment by Psk-Ita** [comment]
You should get in touch with MiXplorer developer
(https://mixplorer.com/#intro)
note also MiXplorer has theme, just check if one of the available ones fits better your needs

**Comment by derei** [comment]
I know it has theming, but it controls page color for all tabs, it's only one parameter and it doesn't distinguish between focused/unfocused.
