### ISSUE TITLE
FAIL Andorid 7

### ISSUE THREAD

**Issue by juanpc2018** [Psk-Ita/MiXplorer#8]
does Not allow to Click
[Ok i will Help] [No i dont want to Help]..

buttons change color when pressed, but nothing happens.

**Comment by Psk-Ita** [comment]
ouch, android 7!!!
I am sorry, I don't have idea what happends on your device
but I can suggest to unzip the file, navigate to /system/app
manually install the apks that are still compliant on your device
sorry I can not be more details because of old OS
